//! The shortcut registry and the `KeyBinding` set generated from it.
//!
//! `ShortcutDef` / `Scope` / `Screen` / `SHORTCUTS` are copied from
//! `src/gui/update/shortcuts.rs:104-...` **unchanged in content** — the
//! registry stays the single source of truth for both bindings and (Plan 08's)
//! shortcut overlay, exactly as spec §5 requires. Only the *mechanism*
//! changed: iced's modifier-independent key names become gpui keystroke
//! strings, and the platform modifier is applied here rather than by a
//! `global_mods` predicate at match time.

use gpui::{actions, KeyBinding};

// ── platform chords ──────────────────────────────────────────────────────

/// The platform's global-shortcut modifier: Cmd on macOS (matching the Cmd+C /
/// Cmd+V pair), Ctrl+Shift elsewhere (matching Ctrl+Shift+C / Ctrl+Shift+V, so
/// plain Ctrl chords stay available to the PTY).
/// Port of `global_mods` + `platform_mod_label`.
pub fn platform_mod_prefix() -> &'static str {
    if cfg!(target_os = "macos") {
        "cmd-"
    } else {
        "ctrl-shift-"
    }
}

/// Shared modifier for every `requires_alt` chord: Cmd+Alt (mac) / Ctrl+Alt
/// (elsewhere), independent of `platform_mod_prefix` (which already requires
/// Shift on non-mac and so can't be reused as a base for an Alt chord there).
/// Port of `alt_chord_mods`.
pub fn alt_chord_prefix() -> &'static str {
    if cfg!(target_os = "macos") {
        "cmd-alt-"
    } else {
        "ctrl-alt-"
    }
}

/// Human-readable label for the global-shortcut modifier, for the overlay and
/// the status-bar chip (Plan 08).
pub fn platform_mod_label() -> &'static str {
    if cfg!(target_os = "macos") {
        "cmd"
    } else {
        "ctrl+shift"
    }
}

// ── the registry (ported verbatim) ───────────────────────────────────────

/// App-level actions reachable from the global keyboard layer.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum GlobalShortcut {
    NewSession,
    NewSessionInWorktree,
    Settings,
    ToggleZen,
    ToggleGrid,
    ZoomIn,
    ZoomOut,
    ZoomReset,
    NextSession,
    PrevSession,
    // Vocabulary entries, never constructed by design: these three shortcuts
    // have *dynamic* chords, so their registry rows are display-only
    // (`action: None`) and their bindings are generated by
    // `select_session_bindings`/`grid_bindings` from the payload-carrying
    // action structs of the same name. The variants exist so `ShortcutDef` can
    // still name every shortcut and `binding_for`/`dispatch_on_screen` stay
    // exhaustive over the vocabulary.
    #[allow(dead_code)]
    SelectSession(usize),
    ShortcutOverlay,
    CloseFocusedSession,
    /// Create and focus a new home terminal — mod+Alt+T, reachable from the
    /// agent side or while already showing the terminal tab.
    NewHomeTerminal,
    /// Swap between the home-terminal tab and whatever the agent side was
    /// showing (grid or single session), preserving the other side's context.
    ToggleTerminal,
    /// Open or close the right-docked worktree terminal panel — the keyboard
    /// twin of the session header's `term` button, and the only way in while
    /// zen hides that button. Live on every screen but the grid, which never
    /// renders the panel at all (the handler propagates there). Scoped
    /// `Global` in the registry like every
    /// other letter shortcut: `Screen(Zen)` cannot honestly describe a
    /// runtime-gated chord, since off-screen a `ctrl-shift-letter` row is
    /// swallowed by `key_to_bytes` before it would ever reach the PTY (see
    /// `is_non_mac_platform_mod_letter_row` in `keyboard_matrix.rs`). The
    /// `on_action` handler in `workspace.rs` gates on grid view itself.
    ToggleTermPanel,
    /// Select the first session currently waiting for input, in tree order.
    JumpToWaitingSession,
    /// Move keyboard focus between grid tiles by `(dx, dy)`. Grid screen only.
    /// Display-only in the registry — see `SelectSession` above.
    #[allow(dead_code)]
    GridMove(i32, i32),
    /// Swap the focused tile with its neighbor by `(dx, dy)`. Grid screen only.
    /// Display-only in the registry — see `SelectSession` above.
    #[allow(dead_code)]
    GridSwap(i32, i32),
    /// Scroll the focused session by half a page (`true` = up).
    ScrollHalfPage(bool),
    /// Open the command palette straight into the "switch to session"
    /// drill-in. Zen-only — see `PaletteRow::SwitchToSession`.
    SwitchSession,
}

/// Coarse "which screen am I on" model, derived from existing UI flags.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Screen {
    Grid,
    Workspace,
    Zen,
}

impl Screen {
    /// Section header label used in the overlay when >1 scope is visible.
    pub fn label(self) -> &'static str {
        match self {
            Screen::Grid => "grid",
            Screen::Workspace => "workspace",
            Screen::Zen => "zen",
        }
    }

    /// gpui key-context string for this screen. Modal contexts arrive in
    /// Plan 08.
    pub fn key_context(self) -> &'static str {
        match self {
            Screen::Grid => "Grid",
            Screen::Workspace => "Workspace",
            Screen::Zen => "Zen",
        }
    }
}

/// Where a shortcut applies. A shortcut may list several scopes.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Scope {
    Global,
    Screen(Screen),
}

/// One row of the shortcut registry — single source of truth for both the
/// key bindings (behavior) and the shortcut overlay (display).
pub struct ShortcutDef {
    /// `None` for display-only rows (the `1–9` row and the chords handled
    /// dynamically by the matcher).
    pub action: Option<GlobalShortcut>,
    /// Key names. Empty for display-only rows, and for `ToggleZen`, whose
    /// chord is Enter (`display_keys` carries it; see `keystrokes_for`).
    pub triggers: &'static [&'static str],
    /// Key label shown in the overlay; the platform modifier is prepended at
    /// render time (e.g. `"n"` -> `"cmd+n"`).
    pub display_keys: &'static str,
    pub description: &'static str,
    pub scopes: &'static [Scope],
    /// When true, this shortcut layers Alt on top of the platform's global
    /// modifier (e.g. Cmd+Alt+N / Ctrl+Alt+N) rather than using the plain
    /// platform modifier.
    pub requires_alt: bool,
    /// When true, `display_keys` is the complete chord text and the overlay
    /// renders it verbatim instead of prepending the platform modifier.
    pub literal: bool,
}

const G: &[Scope] = &[Scope::Global];

/// Single source of truth for behavioral matching and overlay display. Order
/// matches the overlay's reading order.
pub const SHORTCUTS: &[ShortcutDef] = &[
    ShortcutDef {
        action: Some(GlobalShortcut::NewSession),
        triggers: &["p", "P"],
        display_keys: "p",
        description: "New session",
        scopes: G,
        requires_alt: false,
        literal: false,
    },
    ShortcutDef {
        action: Some(GlobalShortcut::NewSessionInWorktree),
        triggers: &["n", "N"],
        display_keys: "n",
        description: "New session in current worktree",
        scopes: G,
        requires_alt: true,
        literal: false,
    },
    ShortcutDef {
        action: Some(GlobalShortcut::SwitchSession),
        triggers: &["s", "S"],
        display_keys: "s",
        description: "Switch to session",
        scopes: G,
        requires_alt: false,
        literal: false,
    },
    ShortcutDef {
        action: Some(GlobalShortcut::NextSession),
        triggers: &["j", "J"],
        display_keys: "j",
        description: "Next session",
        scopes: G,
        requires_alt: false,
        literal: false,
    },
    ShortcutDef {
        action: Some(GlobalShortcut::PrevSession),
        triggers: &["k", "K"],
        display_keys: "k",
        description: "Previous session",
        scopes: G,
        requires_alt: false,
        literal: false,
    },
    // Display-only: the matcher handles 1–9 dynamically.
    ShortcutDef {
        action: None,
        triggers: &[],
        display_keys: "1–9",
        description: "Select nth session",
        scopes: G,
        requires_alt: false,
        literal: false,
    },
    ShortcutDef {
        action: Some(GlobalShortcut::ToggleGrid),
        triggers: &["g", "G"],
        display_keys: "g",
        description: "Toggle grid view",
        scopes: G,
        requires_alt: false,
        literal: false,
    },
    ShortcutDef {
        action: Some(GlobalShortcut::ToggleZen),
        triggers: &[],
        display_keys: "enter",
        description: "Toggle zen mode",
        scopes: G,
        requires_alt: false,
        literal: false,
    },
    ShortcutDef {
        action: Some(GlobalShortcut::Settings),
        triggers: &[","],
        display_keys: ",",
        description: "Settings",
        scopes: G,
        requires_alt: false,
        literal: false,
    },
    ShortcutDef {
        action: Some(GlobalShortcut::ZoomIn),
        triggers: &["=", "+"],
        display_keys: "=",
        description: "Zoom in",
        scopes: G,
        requires_alt: false,
        literal: false,
    },
    ShortcutDef {
        action: Some(GlobalShortcut::ZoomOut),
        triggers: &["-", "_"],
        display_keys: "-",
        description: "Zoom out",
        scopes: G,
        requires_alt: false,
        literal: false,
    },
    ShortcutDef {
        action: Some(GlobalShortcut::ZoomReset),
        triggers: &["0"],
        display_keys: "0",
        description: "Reset zoom",
        scopes: G,
        requires_alt: false,
        literal: false,
    },
    ShortcutDef {
        action: Some(GlobalShortcut::ShortcutOverlay),
        triggers: &["/", "?"],
        display_keys: "/",
        description: "This overlay",
        scopes: G,
        requires_alt: false,
        literal: false,
    },
    ShortcutDef {
        action: Some(GlobalShortcut::CloseFocusedSession),
        triggers: &["w", "W"],
        display_keys: "w",
        description: "close focused session / terminal",
        scopes: G,
        requires_alt: false,
        literal: false,
    },
    ShortcutDef {
        action: Some(GlobalShortcut::ToggleTerminal),
        triggers: &["t", "T"],
        display_keys: "t",
        description: "toggle terminal",
        scopes: G,
        requires_alt: false,
        literal: false,
    },
    ShortcutDef {
        action: Some(GlobalShortcut::ToggleTermPanel),
        triggers: &["e", "E"],
        display_keys: "e",
        description: "toggle side terminal",
        scopes: G,
        requires_alt: false,
        literal: false,
    },
    ShortcutDef {
        action: Some(GlobalShortcut::NewHomeTerminal),
        triggers: &["t", "T"],
        display_keys: "t",
        description: "New terminal",
        scopes: G,
        requires_alt: true,
        literal: false,
    },
    ShortcutDef {
        action: Some(GlobalShortcut::JumpToWaitingSession),
        triggers: &["'"],
        display_keys: "'",
        description: "Jump to session needing you",
        scopes: G,
        requires_alt: false,
        literal: false,
    },
    // Display-only: plain PageUp/PageDown/Home/End (no Shift) must fall
    // through to the PTY, so these live outside the binding set.
    ShortcutDef {
        action: None,
        triggers: &[],
        display_keys: "shift+pgup/pgdn",
        description: "Scroll session by page",
        scopes: G,
        requires_alt: false,
        literal: true,
    },
    ShortcutDef {
        action: None,
        triggers: &[],
        display_keys: "shift+home/end",
        description: "Scroll to top / bottom",
        scopes: G,
        requires_alt: false,
        literal: true,
    },
    ShortcutDef {
        action: Some(GlobalShortcut::ScrollHalfPage(true)),
        triggers: &["u", "U"],
        display_keys: "u",
        description: "Scroll half page up",
        scopes: G,
        requires_alt: false,
        literal: false,
    },
    ShortcutDef {
        action: Some(GlobalShortcut::ScrollHalfPage(false)),
        triggers: &["d", "D"],
        display_keys: "d",
        description: "Scroll half page down",
        scopes: G,
        requires_alt: false,
        literal: false,
    },
    // Display-only: the grid move/swap chords are dynamic (dx/dy per key,
    // swap modifier picks move vs. swap) and are wired in Plan 07.
    ShortcutDef {
        action: None,
        triggers: &[],
        display_keys: "h j k l / ←↓↑→",
        description: "Move focus in grid",
        scopes: &[Scope::Screen(Screen::Grid)],
        requires_alt: false,
        literal: false,
    },
    ShortcutDef {
        action: None,
        triggers: &[],
        display_keys: if cfg!(target_os = "macos") {
            "shift+h j k l / ←↓↑→"
        } else {
            "alt+h j k l / ←↓↑→"
        },
        description: "Move tile in grid",
        scopes: &[Scope::Screen(Screen::Grid)],
        requires_alt: !cfg!(target_os = "macos"),
        literal: false,
    },
    // Display-only: closing the terminal panel must fall through to the PTY.
    ShortcutDef {
        action: None,
        triggers: &[],
        display_keys: "ctrl+shift+←/→",
        description: "Resize terminal panel",
        scopes: &[Scope::Screen(Screen::Workspace)],
        requires_alt: false,
        literal: true,
    },
    // Display-only: `zen_focus_bindings` generates the actual bindings —
    // mod+→/← carry distinct actions (`FocusSidePanel`/`FocusAgentPane`), not
    // one registry action, so this row stays outside the action-driven table.
    ShortcutDef {
        action: None,
        triggers: &[],
        display_keys: "←/→",
        description: "focus side terminal / agent",
        scopes: &[Scope::Screen(Screen::Zen)],
        requires_alt: false,
        literal: false,
    },
];

/// Derive the coarse screen from UI flags. Zen wins over grid: while chrome is
/// hidden the user is in zen regardless of `grid_view`.
pub fn screen_from_flags(chrome_visible: bool, grid_view: bool) -> Screen {
    if !chrome_visible {
        Screen::Zen
    } else if grid_view {
        Screen::Grid
    } else {
        Screen::Workspace
    }
}

/// True if a shortcut whose registry row lists `scopes` may fire on `screen`.
// Exercised only by this module's `#[cfg(test)]` scope table; the live path
// compares key contexts through `contexts_for` instead.
#[allow(dead_code)]
pub fn scope_allows(scopes: &[Scope], screen: Screen) -> bool {
    scopes
        .iter()
        .any(|s| matches!(s, Scope::Global) || *s == Scope::Screen(screen))
}

// ── registry -> keystrokes ───────────────────────────────────────────────

/// iced trigger name -> gpui key name. The registry lists the shifted twin of
/// each key (`"p", "P"` / `"=", "+"`) because iced matches the produced
/// character; gpui keystrokes name the *unshifted* key and carry modifiers
/// separately, so both twins collapse onto one keystroke.
fn gpui_key(trigger: &str) -> Option<String> {
    let mut chars = trigger.chars();
    let (c, rest) = (chars.next()?, chars.next());
    if rest.is_some() {
        // Multi-char names ("enter") pass through as-is.
        return Some(trigger.to_string());
    }
    Some(match c {
        'A'..='Z' | 'a'..='z' => c.to_ascii_lowercase().to_string(),
        '+' => "=".to_string(),
        '_' => "-".to_string(),
        '?' => "/".to_string(),
        _ => c.to_string(),
    })
}

/// US-layout shifted twin of each punctuation/digit key.
///
/// gpui's Linux backend reports the *shifted glyph* as the keystroke key **and
/// drops the shift modifier** for any key whose lowercase and uppercase forms
/// are equal (`platform.rs`: `if key.to_lowercase() == key.to_uppercase() {
/// modifiers.shift = false }`). So Ctrl+Shift+`,` arrives as the keystroke
/// `ctrl-<` — not `ctrl-shift-<`, and never as `ctrl-shift-,`. Binding match is
/// exact on the whole keystroke string, so on non-mac every punctuation/digit
/// chord must also be bound as *platform prefix minus shift* + twin glyph, and
/// that twin form is in practice the only one that can ever fire. Letters are
/// unaffected: they keep their shift modifier and match the base form.
///
/// ponytail: this assumes a US layout. Per-layout correctness would need a
/// runtime xkb lookup of what each keycode produces with Shift held; not worth
/// it here.
const SHIFTED_TWINS: &[(char, char)] = &[
    (',', '<'),
    ('.', '>'),
    ('/', '?'),
    ('=', '+'),
    ('-', '_'),
    (';', ':'),
    ('\'', '"'),
    ('[', '{'),
    (']', '}'),
    ('\\', '|'),
    ('`', '~'),
    ('0', ')'),
    ('1', '!'),
    ('2', '@'),
    ('3', '#'),
    ('4', '$'),
    ('5', '%'),
    ('6', '^'),
    ('7', '&'),
    ('8', '*'),
    ('9', '('),
];

/// The shifted twin of a single-char key, if it has one.
fn shifted_twin(key: &str) -> Option<String> {
    let mut chars = key.chars();
    let c = chars.next()?;
    if chars.next().is_some() {
        return None;
    }
    SHIFTED_TWINS
        .iter()
        .find(|(base, _)| *base == c)
        .map(|(_, t)| t.to_string())
}

/// True when the platform modifier itself carries Shift (non-mac), and so the
/// shifted-twin keys must be bound alongside the base keys.
fn needs_shifted_twins() -> bool {
    !cfg!(target_os = "macos")
}

/// The prefix a shifted-twin keystroke carries: the platform prefix with its
/// `shift-` removed, because gpui strips the shift modifier for exactly these
/// keys (see `SHIFTED_TWINS`). `ctrl-shift-` -> `ctrl-`.
fn twin_prefix(prefix: &str) -> String {
    prefix.replace("shift-", "")
}

/// Every distinct gpui keystroke this row binds, already carrying its
/// platform modifier. Empty for display-only rows.
pub fn keystrokes_for(def: &ShortcutDef) -> Vec<String> {
    if def.action.is_none() {
        return Vec::new();
    }
    let prefix = if def.requires_alt {
        alt_chord_prefix()
    } else {
        platform_mod_prefix()
    };
    // `ToggleZen` is the one bound row with no `triggers`: iced matches Enter
    // outside the trigger table, so its key lives in `display_keys`.
    let raw: Vec<&str> = if def.triggers.is_empty() {
        vec![def.display_keys]
    } else {
        def.triggers.to_vec()
    };
    let mut out: Vec<String> = Vec::new();
    let push = |ks: String, out: &mut Vec<String>| {
        if !out.contains(&ks) {
            out.push(ks);
        }
    };
    for t in raw {
        if let Some(k) = gpui_key(t) {
            push(format!("{prefix}{k}"), &mut out);
            // Only the platform prefix carries Shift; the alt chord does not.
            if needs_shifted_twins() && !def.requires_alt {
                if let Some(tw) = shifted_twin(&k) {
                    push(format!("{}{tw}", twin_prefix(prefix)), &mut out);
                }
            }
        }
    }
    out
}

/// Key contexts a row binds into. `Scope::Global` binds with no context (so it
/// fires anywhere); `Scope::Screen(s)` binds into that screen's context.
pub fn contexts_for(def: &ShortcutDef) -> Vec<Option<&'static str>> {
    let mut out: Vec<Option<&'static str>> = Vec::new();
    for s in def.scopes {
        let ctx = match s {
            Scope::Global => None,
            Scope::Screen(screen) => Some(screen.key_context()),
        };
        if !out.contains(&ctx) {
            out.push(ctx);
        }
    }
    out
}

// ── actions ──────────────────────────────────────────────────────────────

actions!(
    grove,
    [
        NewSession,
        NewSessionInWorktree,
        SwitchSession,
        NextSession,
        PrevSession,
        ToggleGrid,
        ToggleZen,
        Settings,
        ZoomIn,
        ZoomOut,
        ZoomReset,
        ShortcutOverlay,
        CloseFocusedSession,
        ToggleTerminal,
        ToggleTermPanel,
        NewHomeTerminal,
        JumpToWaitingSession,
        ScrollHalfPageUp,
        ScrollHalfPageDown,
        FocusSidePanel,
        FocusAgentPane,
    ]
);

// The keys a *modal* claims back from a focused `Input`.
//
// gpui-component binds `up`/`down`/`left`/`right`/`tab`/`shift-tab`/`enter`
// in the plain `"Input"` context, and a matched binding stops dispatch before
// the modal layer's bubble-phase `on_key_down` ever runs. These actions are
// bound in the **descendant** context `"<ModalKind> > Input"`, which matches
// at the same node and therefore wins on registration order (Grove binds
// after `gpui_component::init`; see `app.rs`). `ModalLayer` handles each one
// by feeding the equivalent keystroke back through the same verdict table its
// `on_key_down` uses, so there is exactly one decision path.
actions!(
    grove_modal,
    [
        ModalUp,
        ModalDown,
        ModalLeft,
        ModalRight,
        ModalTab,
        ModalShiftTab,
        ModalEnter,
    ]
);

/// `mod+1..9` — the one **data-carrying** action (Plan 03 deviation 3). The
/// `actions!` macro only generates unit structs, so this one is derived by hand.
/// `no_json` keeps the derive off `serde`/`schemars`, which grove-gpui does not
/// depend on; grove has no JSON keymap to load from.
#[derive(Clone, Debug, Default, PartialEq, gpui::Action)]
#[action(namespace = grove, no_json)]
pub struct SelectSession {
    /// 1-based, as displayed. Out of range is a no-op, never a clamp.
    pub index: usize,
}

/// Move keyboard focus one tile in the grid. The second data-carrying action
/// (carried amendment 3): gpui `actions!` only generates unit structs, and this
/// one carries `(dx, dy)`.
#[derive(Clone, Debug, Default, PartialEq, gpui::Action)]
#[action(namespace = grove, no_json)]
pub struct GridMove {
    pub dx: i32,
    pub dy: i32,
}

/// Swap the focused tile with its neighbor. Same shape as [`GridMove`]; the
/// modifier is what tells them apart (`grid_swap_mods`, `shortcuts.rs:25-32`).
#[derive(Clone, Debug, Default, PartialEq, gpui::Action)]
#[action(namespace = grove, no_json)]
pub struct GridSwap {
    pub dx: i32,
    pub dy: i32,
}

/// Ctrl+Shift+←/→ steps the terminal panel by ±`TERM_PANEL_PORTION_STEP`.
/// Bound **only** in the workspace context (recorded ambiguity 4), so that
/// closing the panel lets those keys fall through to the PTY exactly as
/// `term_panel_resize_delta`'s `Screen::Workspace` check does
/// (`pty_input.rs:413-423`).
#[derive(Clone, Debug, Default, PartialEq, gpui::Action)]
#[action(namespace = grove, no_json)]
pub struct AdjustTermPanel {
    pub delta: i16,
}

/// The directional keys the grid accepts and the `(dx, dy)` each carries —
/// h/j/k/l **and** the four arrows, exactly the by-hand arm at
/// `shortcuts.rs:446-463`.
pub const GRID_DIRECTIONS: &[(&str, i32, i32)] = &[
    ("h", -1, 0),
    ("l", 1, 0),
    ("k", 0, -1),
    ("j", 0, 1),
    ("left", -1, 0),
    ("right", 1, 0),
    ("up", 0, -1),
    ("down", 0, 1),
];

/// The chord prefixes that mean "swap" rather than "move". Port of
/// `grid_swap_mods` (`shortcuts.rs:25-36`): on macOS the swap modifier is Alt
/// **or** Shift, because Cmd+Opt+H collides with the OS "Hide Others"
/// shortcut; elsewhere [`platform_mod_prefix`] already carries Shift, so only
/// Alt distinguishes the two.
pub fn grid_swap_prefixes() -> Vec<String> {
    if cfg!(target_os = "macos") {
        vec!["cmd-alt-".to_string(), "cmd-shift-".to_string()]
    } else {
        vec![format!("{}alt-", platform_mod_prefix())]
    }
}

/// The grid's move/swap bindings, generated from the registry's two
/// display-only grid rows and scoped to the `Grid` key context.
fn grid_bindings() -> Vec<KeyBinding> {
    let ctx = Some(Screen::Grid.key_context());
    let prefix = platform_mod_prefix();
    let swap_prefixes = grid_swap_prefixes();
    let mut out = Vec::new();
    for &(key, dx, dy) in GRID_DIRECTIONS {
        out.push(KeyBinding::new(
            &format!("{prefix}{key}"),
            GridMove { dx, dy },
            ctx,
        ));
        for sp in &swap_prefixes {
            out.push(KeyBinding::new(
                &format!("{sp}{key}"),
                GridSwap { dx, dy },
                ctx,
            ));
        }
    }
    out
}

/// The panel-resize step, workspace context only (recorded ambiguity 4). The
/// registry row stays display-only for the Plan 08 overlay.
fn term_panel_bindings() -> Vec<KeyBinding> {
    #[allow(clippy::cast_possible_wrap)]
    let step = crate::entities::workspace_state::TERM_PANEL_PORTION_STEP as i16;
    let ctx = Some(Screen::Workspace.key_context());
    vec![
        KeyBinding::new("ctrl-shift-right", AdjustTermPanel { delta: step }, ctx),
        KeyBinding::new("ctrl-shift-left", AdjustTermPanel { delta: -step }, ctx),
    ]
}

/// Zen-only keyboard focus for the side terminal panel: mod+→ moves focus
/// onto the panel, mod+← moves it back to the agent. Focus only — opening and
/// closing the panel is `ToggleTermPanel`'s job. Scoped to `Zen` alone, so the
/// same chords stay free for `AdjustTermPanel` in the workspace context.
fn zen_focus_bindings() -> Vec<KeyBinding> {
    let ctx = Some(Screen::Zen.key_context());
    let prefix = platform_mod_prefix();
    vec![
        KeyBinding::new(&format!("{prefix}right"), FocusSidePanel, ctx),
        KeyBinding::new(&format!("{prefix}left"), FocusAgentPane, ctx),
    ]
}

/// The `"<ModalKind> > Input"` bindings that hand the modal back the keys a
/// focused field would otherwise swallow. Derived from
/// [`crate::views::modals::input::InputPolicy`] so the bindings and the
/// field's own policy can never disagree.
///
/// A multiline buffer claims nothing: Enter is a newline, ↑/↓ move the caret
/// and Tab indents (`modals::input`'s module doc).
pub fn modal_input_bindings() -> Vec<KeyBinding> {
    use crate::views::modals::input::{InputPolicy, ModalInput};

    let mut out = Vec::new();
    for kind in crate::modal::ModalKind::ALL {
        let policy = InputPolicy::for_modal(kind);
        if policy.multi_line {
            continue;
        }
        let ctx = ModalInput::override_context(kind);
        let ctx = Some(ctx.as_str());
        out.push(KeyBinding::new("up", ModalUp, ctx));
        out.push(KeyBinding::new("down", ModalDown, ctx));
        out.push(KeyBinding::new("enter", ModalEnter, ctx));
        if policy.wants_tab {
            out.push(KeyBinding::new("tab", ModalTab, ctx));
            out.push(KeyBinding::new("shift-tab", ModalShiftTab, ctx));
        }
        if policy.wants_arrows {
            out.push(KeyBinding::new("left", ModalLeft, ctx));
            out.push(KeyBinding::new("right", ModalRight, ctx));
        }
    }
    out
}

/// The nine `mod+1..9` bindings, generated from the registry's display-only
/// `1–9` row so the registry stays the single source of truth.
fn select_session_bindings() -> Vec<KeyBinding> {
    let prefix = platform_mod_prefix();
    let mut out = Vec::new();
    for index in 1..=9usize {
        let key = index.to_string();
        out.push(KeyBinding::new(
            &format!("{prefix}{key}"),
            SelectSession { index },
            None,
        ));
        // See `SHIFTED_TWINS`: on non-mac the chord carries Shift, so the
        // digits arrive as `!@#$%^&*(` with the shift modifier stripped —
        // `ctrl-!`, not `ctrl-shift-!`. This is the form that actually fires.
        if needs_shifted_twins() {
            if let Some(tw) = shifted_twin(&key) {
                out.push(KeyBinding::new(
                    &format!("{}{tw}", twin_prefix(prefix)),
                    SelectSession { index },
                    None,
                ));
            }
        }
    }
    out
}

/// One `KeyBinding` for a registry action, or `None` for the shortcuts whose
/// chords are dynamic (`SelectSession`, `GridMove`, `GridSwap`) and therefore
/// never reach a static binding.
fn binding_for(keystroke: &str, sc: GlobalShortcut, ctx: Option<&str>) -> Option<KeyBinding> {
    use GlobalShortcut as S;
    Some(match sc {
        S::NewSession => KeyBinding::new(keystroke, NewSession, ctx),
        S::NewSessionInWorktree => KeyBinding::new(keystroke, NewSessionInWorktree, ctx),
        S::SwitchSession => KeyBinding::new(keystroke, SwitchSession, ctx),
        S::NextSession => KeyBinding::new(keystroke, NextSession, ctx),
        S::PrevSession => KeyBinding::new(keystroke, PrevSession, ctx),
        S::ToggleGrid => KeyBinding::new(keystroke, ToggleGrid, ctx),
        S::ToggleZen => KeyBinding::new(keystroke, ToggleZen, ctx),
        S::Settings => KeyBinding::new(keystroke, Settings, ctx),
        S::ZoomIn => KeyBinding::new(keystroke, ZoomIn, ctx),
        S::ZoomOut => KeyBinding::new(keystroke, ZoomOut, ctx),
        S::ZoomReset => KeyBinding::new(keystroke, ZoomReset, ctx),
        S::ShortcutOverlay => KeyBinding::new(keystroke, ShortcutOverlay, ctx),
        S::CloseFocusedSession => KeyBinding::new(keystroke, CloseFocusedSession, ctx),
        S::ToggleTerminal => KeyBinding::new(keystroke, ToggleTerminal, ctx),
        S::ToggleTermPanel => KeyBinding::new(keystroke, ToggleTermPanel, ctx),
        S::NewHomeTerminal => KeyBinding::new(keystroke, NewHomeTerminal, ctx),
        S::JumpToWaitingSession => KeyBinding::new(keystroke, JumpToWaitingSession, ctx),
        S::ScrollHalfPage(true) => KeyBinding::new(keystroke, ScrollHalfPageUp, ctx),
        S::ScrollHalfPage(false) => KeyBinding::new(keystroke, ScrollHalfPageDown, ctx),
        S::SelectSession(_) | S::GridMove(..) | S::GridSwap(..) => return None,
    })
}

/// The registry is the only source of key bindings — a shortcut that exists in
/// SHORTCUTS but has no binding here is a bug, not a feature. Asserted below.
pub fn bindings() -> Vec<KeyBinding> {
    let mut out = Vec::new();
    for def in SHORTCUTS {
        let Some(sc) = def.action else { continue };
        for ctx in contexts_for(def) {
            for ks in keystrokes_for(def) {
                if let Some(b) = binding_for(&ks, sc, ctx) {
                    out.push(b);
                }
            }
        }
    }
    out.extend(select_session_bindings());
    out.extend(grid_bindings());
    out.extend(term_panel_bindings());
    out.extend(zen_focus_bindings());
    // Last, so a modal's `"… > Input"` binding also out-ranks anything above
    // it on a registration-order tie.
    out.extend(modal_input_bindings());
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::HashSet;

    /// Every bound row must actually produce a keystroke — the drift guard the
    /// "cannot drift" claim rests on.
    #[test]
    fn every_actionable_row_produces_a_binding() {
        for def in SHORTCUTS {
            let Some(sc) = def.action else { continue };
            let ks = keystrokes_for(def);
            assert!(
                !ks.is_empty(),
                "{:?} ({}) produced no keystroke",
                sc,
                def.description
            );
            for k in &ks {
                assert!(
                    binding_for(k, sc, None).is_some(),
                    "{sc:?} has no KeyBinding arm"
                );
            }
        }
        assert!(!bindings().is_empty());
    }

    /// Plan 07 carried amendment 3: the grid carve-out is **deleted**. Every
    /// registry action now has a `KeyBinding`, with no exceptions; the
    /// dynamic-chord ones are bound through their own payload actions.
    #[test]
    fn no_registry_action_is_left_unbound() {
        for def in SHORTCUTS {
            let Some(sc) = def.action else { continue };
            assert!(
                binding_for("ctrl-x", sc, None).is_some(),
                "{sc:?} has no binding"
            );
        }
        // Nine digits, plus their shifted twins wherever the platform chord
        // already carries Shift — the twins bound *without* `shift-`, since
        // gpui strips it for digit keys (`ctrl-!`, not `ctrl-shift-!`).
        let sel = select_session_bindings();
        assert_eq!(sel.len(), if needs_shifted_twins() { 18 } else { 9 });
        if needs_shifted_twins() {
            let strokes: Vec<String> = sel
                .iter()
                .map(|b| {
                    b.keystrokes()
                        .iter()
                        .map(gpui::KeybindingKeystroke::unparse)
                        .collect::<Vec<_>>()
                        .join(" ")
                })
                .collect();
            assert!(strokes.contains(&"ctrl-!".to_string()), "{strokes:?}");
            assert!(strokes.contains(&"ctrl-(".to_string()), "{strokes:?}");
            assert!(!strokes.iter().any(|s| s.starts_with("ctrl-shift-!")));
        }
        // 8 directions × (1 move + 1 swap chord per platform modifier set).
        let per_dir = 1 + grid_swap_prefixes().len();
        assert_eq!(grid_bindings().len(), GRID_DIRECTIONS.len() * per_dir);
        assert_eq!(term_panel_bindings().len(), 2);
        assert_eq!(zen_focus_bindings().len(), 2);
    }

    /// Each direction key carries the `(dx, dy)` the by-hand iced arm gave it
    /// (`shortcuts.rs:446-463`), and h/j/k/l agree with their arrow twins.
    #[test]
    fn every_grid_direction_carries_its_delta() {
        let by_key = |k: &str| {
            GRID_DIRECTIONS
                .iter()
                .find(|(key, ..)| *key == k)
                .map(|&(_, dx, dy)| (dx, dy))
        };
        assert_eq!(by_key("h"), Some((-1, 0)));
        assert_eq!(by_key("l"), Some((1, 0)));
        assert_eq!(by_key("k"), Some((0, -1)));
        assert_eq!(by_key("j"), Some((0, 1)));
        assert_eq!(by_key("left"), by_key("h"));
        assert_eq!(by_key("right"), by_key("l"));
        assert_eq!(by_key("up"), by_key("k"));
        assert_eq!(by_key("down"), by_key("j"));
        assert_eq!(GRID_DIRECTIONS.len(), 8);
    }

    /// `grid_swap_mods` (`shortcuts.rs:25-36`): Alt *or* Shift on macOS, Alt
    /// alone elsewhere — and never the same chord as a plain move.
    #[test]
    fn the_swap_modifier_set_is_platform_correct() {
        let swap = grid_swap_prefixes();
        if cfg!(target_os = "macos") {
            assert_eq!(swap, vec!["cmd-alt-".to_string(), "cmd-shift-".to_string()]);
        } else {
            assert_eq!(swap, vec!["ctrl-shift-alt-".to_string()]);
        }
        for p in &swap {
            assert_ne!(p.as_str(), platform_mod_prefix());
        }
    }

    /// Recorded ambiguity 4: the panel step is workspace-scoped, so with the
    /// panel closed the chord falls through to the PTY, and it never shadows
    /// the grid's own arrow chords.
    #[test]
    fn the_panel_step_is_workspace_scoped_only() {
        let Some(row) = SHORTCUTS
            .iter()
            .find(|d| d.description == "Resize terminal panel")
        else {
            unreachable!("the panel-resize row must stay in the registry");
        };
        // Still display-only — the binding is hand-made, not registry-derived.
        assert!(row.action.is_none());
        assert!(keystrokes_for(row).is_empty());
        assert_eq!(row.scopes, &[Scope::Screen(Screen::Workspace)]);
        assert!(!scope_allows(row.scopes, Screen::Grid));
        assert!(!scope_allows(row.scopes, Screen::Zen));
    }

    /// The terminal tab is **not** a fourth `Screen` (Task 3 Step 3): iced's
    /// own enum has exactly three variants (`shortcuts.rs:87-91`) and
    /// `terminal_focused` is orthogonal to it, so `screen_from_flags` and
    /// `contexts_for` already agree and no fifth state is invented here.
    #[test]
    fn the_screen_model_has_exactly_three_states() {
        for screen in [Screen::Grid, Screen::Workspace, Screen::Zen] {
            assert!(!screen.key_context().is_empty());
            assert!(!screen.label().is_empty());
        }
        // Every context a registry row can ask for is one of the three.
        for def in SHORTCUTS {
            for ctx in contexts_for(def).into_iter().flatten() {
                assert!(
                    ["Grid", "Workspace", "Zen"].contains(&ctx),
                    "unexpected key context {ctx}"
                );
            }
        }
    }

    #[test]
    fn no_two_rows_share_a_keystroke_in_the_same_context() {
        let mut seen: HashSet<(Option<&'static str>, String)> = HashSet::new();
        for def in SHORTCUTS {
            if def.action.is_none() {
                continue;
            }
            for ctx in contexts_for(def) {
                for ks in keystrokes_for(def) {
                    assert!(
                        seen.insert((ctx, ks.clone())),
                        "duplicate keystroke {ks} in context {ctx:?} ({})",
                        def.description
                    );
                }
            }
        }
    }

    #[test]
    fn shifted_twins_collapse_onto_one_keystroke() {
        let Some(new_session) = SHORTCUTS
            .iter()
            .find(|d| d.action == Some(GlobalShortcut::NewSession))
        else {
            unreachable!("GlobalShortcut::NewSession must have a registry row");
        };
        assert_eq!(new_session.triggers, &["p", "P"]);
        assert_eq!(keystrokes_for(new_session).len(), 1);

        let Some(zoom_in) = SHORTCUTS
            .iter()
            .find(|d| d.action == Some(GlobalShortcut::ZoomIn))
        else {
            unreachable!("GlobalShortcut::ZoomIn must have a registry row");
        };
        let p = platform_mod_prefix();
        let expected = if needs_shifted_twins() {
            // The twin drops `shift-`: gpui reports Ctrl+Shift+= as `ctrl-+`.
            vec![format!("{p}="), format!("{}+", twin_prefix(p))]
        } else {
            vec![format!("{p}=")]
        };
        assert_eq!(keystrokes_for(zoom_in), expected);
    }

    /// On Linux/Windows the platform chord carries Shift, gpui reports the
    /// *shifted glyph* as the keystroke key **and strips the shift modifier**
    /// — so Ctrl+Shift+, arrives as `ctrl-<` and only that form can reach
    /// `Settings`.
    #[test]
    fn shifted_twins_are_also_bound_on_non_mac() {
        let Some(settings) = SHORTCUTS
            .iter()
            .find(|d| d.action == Some(GlobalShortcut::Settings))
        else {
            unreachable!("GlobalShortcut::Settings must have a registry row");
        };
        let p = platform_mod_prefix();
        let ks = keystrokes_for(settings);
        assert!(ks.contains(&format!("{p},")));
        assert_eq!(
            ks.contains(&format!("{}<", twin_prefix(p))),
            needs_shifted_twins()
        );
        // Never the shift-carrying form — gpui strips shift for `<`.
        assert!(!ks.contains(&format!("{p}<")));
        if needs_shifted_twins() {
            assert_eq!(twin_prefix(p), "ctrl-");
        }
        // And the whole set must actually parse into bindings.
        assert!(!bindings().is_empty());
        assert_eq!(shifted_twin("1").as_deref(), Some("!"));
        assert_eq!(shifted_twin("enter"), None);
        assert_eq!(shifted_twin("a"), None);
    }

    #[test]
    fn toggle_zen_binds_enter_despite_empty_triggers() {
        let Some(zen) = SHORTCUTS
            .iter()
            .find(|d| d.action == Some(GlobalShortcut::ToggleZen))
        else {
            unreachable!("GlobalShortcut::ToggleZen must have a registry row");
        };
        assert!(zen.triggers.is_empty());
        assert_eq!(
            keystrokes_for(zen),
            vec![format!("{}enter", platform_mod_prefix())]
        );
    }

    #[test]
    fn display_only_rows_bind_nothing() {
        for def in SHORTCUTS.iter().filter(|d| d.action.is_none()) {
            assert!(keystrokes_for(def).is_empty(), "{}", def.description);
        }
    }

    #[test]
    fn alt_rows_use_the_alt_chord() {
        let Some(nht) = SHORTCUTS
            .iter()
            .find(|d| d.action == Some(GlobalShortcut::NewHomeTerminal))
        else {
            unreachable!("GlobalShortcut::NewHomeTerminal must have a registry row");
        };
        assert!(nht.requires_alt);
        assert_eq!(
            keystrokes_for(nht),
            vec![format!("{}t", alt_chord_prefix())]
        );
    }

    #[test]
    fn scoped_rows_get_their_screen_context() {
        let grid_only = ShortcutDef {
            action: Some(GlobalShortcut::ToggleGrid),
            triggers: &["g"],
            display_keys: "g",
            description: "test",
            scopes: &[Scope::Screen(Screen::Grid)],
            requires_alt: false,
            literal: false,
        };
        assert_eq!(contexts_for(&grid_only), vec![Some("Grid")]);
        assert!(scope_allows(grid_only.scopes, Screen::Grid));
        assert!(!scope_allows(grid_only.scopes, Screen::Zen));
        assert!(scope_allows(G, Screen::Zen));
    }

    #[test]
    fn screen_from_flags_prefers_zen() {
        assert_eq!(screen_from_flags(false, true), Screen::Zen);
        assert_eq!(screen_from_flags(true, true), Screen::Grid);
        assert_eq!(screen_from_flags(true, false), Screen::Workspace);
        assert_eq!(Screen::Grid.label(), "grid");
    }

    #[test]
    fn platform_labels_agree_with_the_prefix() {
        assert_eq!(
            platform_mod_label().replace('+', "-"),
            platform_mod_prefix().trim_end_matches('-')
        );
    }
}
